// <auto-generated />
using System;
using LibraryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LibraryManagement.Core.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId", "Action");

                    b.ToTable("ActivityLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "DatabaseInitialized",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khởi tạo dữ liệu mẫu của hệ thống.",
                            EmployeeId = 1,
                            EntityName = "Database"
                        },
                        new
                        {
                            Id = 2,
                            Action = "BorrowCreated",
                            CreatedAt = new DateTime(2026, 7, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tạo phiếu mượn PM202607-001.",
                            EmployeeId = 2,
                            EntityId = "1",
                            EntityName = "BorrowSlip"
                        },
                        new
                        {
                            Id = 3,
                            Action = "BookReturned",
                            CreatedAt = new DateTime(2026, 6, 17, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Xử lý trả sách cho phiếu PM202606-001.",
                            EmployeeId = 3,
                            EntityId = "1",
                            EntityName = "ReturnRecord"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nguyễn Nhật Ánh",
                            IsActive = true,
                            Nationality = "Việt Nam",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nam Cao",
                            IsActive = true,
                            Nationality = "Việt Nam",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Robert C. Martin",
                            IsActive = true,
                            Nationality = "Hoa Kỳ",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Yuval Noah Harari",
                            IsActive = true,
                            Nationality = "Israel",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Dale Carnegie",
                            IsActive = true,
                            Nationality = "Hoa Kỳ",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookCode")
                        .IsUnique();

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("\"ISBN\" IS NOT NULL");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_PageCount", "\"PageCount\" > 0");

                            t.HasCheckConstraint("CK_Books_Price", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Books_PublicationYear", "\"PublicationYear\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCode = "S0001",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123451",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 300,
                            Price = 11000000L,
                            PublicationYear = 2019,
                            PublisherId = 1,
                            Title = "Mắt biếc",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BookCode = "S0002",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123452",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 220,
                            Price = 9000000L,
                            PublicationYear = 2020,
                            PublisherId = 1,
                            Title = "Cho tôi xin một vé đi tuổi thơ",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BookCode = "S0003",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123453",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 180,
                            Price = 6500000L,
                            PublicationYear = 2018,
                            PublisherId = 2,
                            Title = "Chí Phèo",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BookCode = "S0004",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123454",
                            IsActive = true,
                            Language = "English",
                            PageCount = 464,
                            Price = 32000000L,
                            PublicationYear = 2021,
                            PublisherId = 3,
                            Title = "Clean Code",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BookCode = "S0005",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123455",
                            IsActive = true,
                            Language = "English",
                            PageCount = 432,
                            Price = 35000000L,
                            PublicationYear = 2022,
                            PublisherId = 3,
                            Title = "Clean Architecture",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BookCode = "S0006",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123456",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 512,
                            Price = 25000000L,
                            PublicationYear = 2020,
                            PublisherId = 3,
                            Title = "Sapiens",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BookCode = "S0007",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123457",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 480,
                            Price = 26000000L,
                            PublicationYear = 2021,
                            PublisherId = 3,
                            Title = "Homo Deus",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BookCode = "S0008",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123458",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 320,
                            Price = 12000000L,
                            PublicationYear = 2022,
                            PublisherId = 1,
                            Title = "Đắc nhân tâm",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BookCode = "S0009",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123459",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 400,
                            Price = 18000000L,
                            PublicationYear = 2019,
                            PublisherId = 3,
                            Title = "Lược sử Việt Nam",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BookCode = "S0010",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9786041123460",
                            IsActive = true,
                            Language = "Tiếng Việt",
                            PageCount = 380,
                            Price = 28000000L,
                            PublicationYear = 2024,
                            PublisherId = 3,
                            Title = "Nhập môn khoa học dữ liệu",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 3
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CopyCode")
                        .IsUnique();

                    b.HasIndex("BookId", "Status");

                    b.ToTable("BookCopies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CopyCode = "BS001-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 11),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-01",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            CopyCode = "BS001-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 12),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-01",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            CopyCode = "BS002-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 13),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-02",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            CopyCode = "BS002-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 14),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-02",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            CopyCode = "BS002-03",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 15),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-02",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            CopyCode = "BS003-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 16),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 1-03",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            CopyCode = "BS004-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 17),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-04",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            CopyCode = "BS004-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 18),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-04",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 4,
                            CopyCode = "BS004-03",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 19),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-04",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BookId = 4,
                            CopyCode = "BS004-04",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 20),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-04",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 5,
                            CopyCode = "BS005-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 21),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-05",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 5,
                            CopyCode = "BS005-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 22),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-05",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 6,
                            CopyCode = "BS006-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 23),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-06",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 6,
                            CopyCode = "BS006-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 24),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-06",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 6,
                            CopyCode = "BS006-03",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 25),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-06",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            BookId = 6,
                            CopyCode = "BS006-04",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 26),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-06",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BookId = 6,
                            CopyCode = "BS006-05",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 27),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 2-06",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BookId = 7,
                            CopyCode = "BS007-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 28),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-07",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            BookId = 8,
                            CopyCode = "BS008-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 29),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-08",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            BookId = 8,
                            CopyCode = "BS008-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 30),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-08",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            BookId = 8,
                            CopyCode = "BS008-03",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 1, 31),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-08",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            BookId = 9,
                            CopyCode = "BS009-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 1),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-09",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            BookId = 9,
                            CopyCode = "BS009-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 2),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 3-09",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            BookId = 10,
                            CopyCode = "BS010-01",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 3),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 4-10",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            BookId = 10,
                            CopyCode = "BS010-02",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 4),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 4-10",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            BookId = 10,
                            CopyCode = "BS010-03",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 5),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 4-10",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            BookId = 10,
                            CopyCode = "BS010-04",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportedAt = new DateOnly(2026, 2, 6),
                            PhysicalCondition = 2,
                            ShelfLocation = "Kệ 4-10",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorrowCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BorrowCode")
                        .IsUnique();

                    b.HasIndex("BorrowDate");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReaderId", "Status");

                    b.ToTable("BorrowSlips", null, t =>
                        {
                            t.HasCheckConstraint("CK_BorrowSlips_ExpectedReturnDate", "\"ExpectedReturnDate\" >= \"BorrowDate\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowCode = "PM202607-001",
                            BorrowDate = new DateOnly(2026, 7, 22),
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            ExpectedReturnDate = new DateOnly(2026, 8, 5),
                            ReaderId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BorrowCode = "PM202607-002",
                            BorrowDate = new DateOnly(2026, 6, 26),
                            CreatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            ExpectedReturnDate = new DateOnly(2026, 7, 10),
                            ReaderId = 2,
                            Status = 4,
                            UpdatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BorrowCode = "PM202606-001",
                            BorrowDate = new DateOnly(2026, 6, 1),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            ExpectedReturnDate = new DateOnly(2026, 6, 15),
                            ReaderId = 3,
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlipDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BookCopyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowSlipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpectedReturnDate");

                    b.HasIndex("BookCopyId", "Status");

                    b.HasIndex("BorrowSlipId", "BookCopyId")
                        .IsUnique();

                    b.ToTable("BorrowSlipDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_BorrowSlipDetails_RenewalCount", "\"RenewalCount\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 1,
                            BorrowSlipId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedReturnDate = new DateOnly(2026, 8, 5),
                            RenewalCount = 0,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BookCopyId = 3,
                            BorrowSlipId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedReturnDate = new DateOnly(2026, 7, 10),
                            RenewalCount = 0,
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ActualReturnDate = new DateOnly(2026, 6, 17),
                            BookCopyId = 7,
                            BorrowSlipId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedReturnDate = new DateOnly(2026, 6, 15),
                            RenewalCount = 0,
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiểu thuyết, truyện ngắn và thơ",
                            IsActive = true,
                            Name = "Văn học",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khoa học tự nhiên và ứng dụng",
                            IsActive = true,
                            Name = "Khoa học",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Công nghệ thông tin và kỹ thuật",
                            IsActive = true,
                            Name = "Công nghệ",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lịch sử Việt Nam và thế giới",
                            IsActive = true,
                            Name = "Lịch sử",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phát triển bản thân và kỹ năng",
                            IsActive = true,
                            Name = "Kỹ năng sống",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 1, 15),
                            Email = "admin@library.local",
                            EmployeeCode = "NV0001",
                            FullName = "Quản trị hệ thống",
                            Gender = 0,
                            IsActive = true,
                            PasswordHash = "$2a$12$PIo15XwwVaJM3R6rcweNauhTHdvEVyxL1dYHEfm4Iu.wyFTSGrDcq",
                            PhoneNumber = "0901000001",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 3, 20),
                            Email = "minhanh@library.local",
                            EmployeeCode = "NV0002",
                            FullName = "Nguyễn Minh Anh",
                            Gender = 2,
                            IsActive = true,
                            PasswordHash = "$2a$12$2plWRQiBcw43230QskNoz.vAwMNgE6JQnEy/PV6TdlyuODmburmS2",
                            PhoneNumber = "0901000002",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "librarian1"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 8, 12),
                            Email = "quocbao@library.local",
                            EmployeeCode = "NV0003",
                            FullName = "Trần Quốc Bảo",
                            Gender = 1,
                            IsActive = true,
                            PasswordHash = "$2a$12$2plWRQiBcw43230QskNoz.vAwMNgE6JQnEy/PV6TdlyuODmburmS2",
                            PhoneNumber = "0901000003",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "librarian2"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowSlipDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FineCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("FineType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PaidAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BorrowSlipDetailId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("FineCode")
                        .IsUnique();

                    b.HasIndex("ReaderId", "Status");

                    b.ToTable("Fines", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fines_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Fines_PaidAmount", "\"PaidAmount\" >= 0");

                            t.HasCheckConstraint("CK_Fines_PaidAmountNotGreaterThanAmount", "\"PaidAmount\" <= \"Amount\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 9000000L,
                            BorrowSlipDetailId = 2,
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByEmployeeId = 2,
                            FineCode = "TP202607-001",
                            FineType = 1,
                            PaidAmount = 0L,
                            ReaderId = 2,
                            Reason = "Quá hạn 18 ngày tính đến ngày tạo dữ liệu mẫu.",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000000L,
                            BorrowSlipDetailId = 3,
                            CreatedAt = new DateTime(2026, 6, 17, 9, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByEmployeeId = 3,
                            FineCode = "TP202606-001",
                            FineType = 1,
                            PaidAmount = 500000L,
                            ReaderId = 3,
                            Reason = "Trả sách quá hạn 2 ngày.",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 6, 17, 9, 35, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.FinePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FineId", "PaymentDate");

                    b.ToTable("FinePayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinePayments_Amount", "\"Amount\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500000L,
                            CreatedAt = new DateTime(2026, 6, 17, 9, 35, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            FineId = 2,
                            Notes = "Thanh toán một phần.",
                            PaymentDate = new DateTime(2026, 6, 17, 9, 35, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 1
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nhà xuất bản Trẻ",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nhà xuất bản Kim Đồng",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nhà xuất bản Tổng hợp TP.HCM",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReaderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReaderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ReaderCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Readers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Readers_ExpirationDate", "\"ExpirationDate\" > \"RegisteredAt\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1996, 1, 10),
                            Email = "reader1@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Lê Hoàng Nam",
                            Gender = 1,
                            PhoneNumber = "0912000001",
                            ReaderCode = "DG0001",
                            ReaderType = 1,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1997, 2, 10),
                            Email = "reader2@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Phạm Thu Hà",
                            Gender = 2,
                            PhoneNumber = "0912000002",
                            ReaderCode = "DG0002",
                            ReaderType = 1,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1998, 3, 10),
                            Email = "reader3@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Đỗ Minh Khang",
                            Gender = 1,
                            PhoneNumber = "0912000003",
                            ReaderCode = "DG0003",
                            ReaderType = 3,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1999, 4, 10),
                            Email = "reader4@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Nguyễn Bảo Ngọc",
                            Gender = 2,
                            PhoneNumber = "0912000004",
                            ReaderCode = "DG0004",
                            ReaderType = 1,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2000, 5, 10),
                            Email = "reader5@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Trần Gia Huy",
                            Gender = 1,
                            PhoneNumber = "0912000005",
                            ReaderCode = "DG0005",
                            ReaderType = 1,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2001, 6, 10),
                            Email = "reader6@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Vũ Khánh Linh",
                            Gender = 2,
                            PhoneNumber = "0912000006",
                            ReaderCode = "DG0006",
                            ReaderType = 2,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2002, 7, 10),
                            Email = "reader7@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Hoàng Anh Tuấn",
                            Gender = 1,
                            PhoneNumber = "0912000007",
                            ReaderCode = "DG0007",
                            ReaderType = 3,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2003, 8, 10),
                            Email = "reader8@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Bùi Mai Chi",
                            Gender = 2,
                            PhoneNumber = "0912000008",
                            ReaderCode = "DG0008",
                            ReaderType = 1,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2004, 9, 10),
                            Email = "reader9@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Đặng Đức Anh",
                            Gender = 1,
                            PhoneNumber = "0912000009",
                            ReaderCode = "DG0009",
                            ReaderType = 4,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2005, 10, 10),
                            Email = "reader10@example.com",
                            ExpirationDate = new DateOnly(2027, 1, 15),
                            FullName = "Phan Ngọc Lan",
                            Gender = 2,
                            PhoneNumber = "0912000010",
                            ReaderCode = "DG0010",
                            ReaderType = 3,
                            RegisteredAt = new DateOnly(2026, 1, 15),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.ReturnRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowSlipDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReturnedCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BorrowSlipDetailId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReturnDate");

                    b.ToTable("ReturnRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReturnRecords_OverdueDays", "\"OverdueDays\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowSlipDetailId = 3,
                            CreatedAt = new DateTime(2026, 6, 17, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            Notes = "Sách được trả trong tình trạng tốt.",
                            OverdueDays = 2,
                            ReturnDate = new DateOnly(2026, 6, 17),
                            ReturnedCondition = 2
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản trị viên hệ thống",
                            IsActive = true,
                            Name = "Administrator",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhân viên thư viện",
                            IsActive = true,
                            Name = "Librarian",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedByEmployeeId");

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Số bản sách được mượn tối đa",
                            Key = "MaximumBorrowedBooks",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "5"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Số ngày mượn mặc định",
                            Key = "DefaultBorrowDays",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "14"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Số lần gia hạn tối đa",
                            Key = "MaximumRenewalCount",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Số ngày cho mỗi lần gia hạn",
                            Key = "RenewalDays",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "7"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mức phạt quá hạn mỗi ngày",
                            Key = "OverdueFinePerDay",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "5000"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hệ số phạt mất sách",
                            Key = "LostBookFineMultiplier",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "2.0"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hệ số phạt hư hỏng",
                            Key = "DamagedBookFineMultiplier",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "0.5"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Thời hạn thẻ độc giả theo tháng",
                            Key = "ReaderCardValidityMonths",
                            UpdatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedByEmployeeId = 1,
                            Value = "12"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.ActivityLog", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Employee", "Employee")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookAuthor", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookCategory", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlip", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Employee", "Employee")
                        .WithMany("BorrowSlips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Reader", "Reader")
                        .WithMany("BorrowSlips")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlipDetail", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.BookCopy", "BookCopy")
                        .WithMany("BorrowSlipDetails")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.BorrowSlip", "BorrowSlip")
                        .WithMany("Details")
                        .HasForeignKey("BorrowSlipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("BorrowSlip");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Employee", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Fine", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.BorrowSlipDetail", "BorrowSlipDetail")
                        .WithMany("Fines")
                        .HasForeignKey("BorrowSlipDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Employee", "CreatedByEmployee")
                        .WithMany("CreatedFines")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Reader", "Reader")
                        .WithMany("Fines")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BorrowSlipDetail");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.FinePayment", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Employee", "Employee")
                        .WithMany("FinePayments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Fine", "Fine")
                        .WithMany("Payments")
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.ReturnRecord", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.BorrowSlipDetail", "BorrowSlipDetail")
                        .WithOne("ReturnRecord")
                        .HasForeignKey("LibraryManagement.Core.Entities.ReturnRecord", "BorrowSlipDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Core.Entities.Employee", "Employee")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BorrowSlipDetail");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.SystemSetting", b =>
                {
                    b.HasOne("LibraryManagement.Core.Entities.Employee", "UpdatedByEmployee")
                        .WithMany("UpdatedSystemSettings")
                        .HasForeignKey("UpdatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpdatedByEmployee");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BookCopy", b =>
                {
                    b.Navigation("BorrowSlipDetails");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlip", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.BorrowSlipDetail", b =>
                {
                    b.Navigation("Fines");

                    b.Navigation("ReturnRecord");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Employee", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("BorrowSlips");

                    b.Navigation("CreatedFines");

                    b.Navigation("FinePayments");

                    b.Navigation("ReturnRecords");

                    b.Navigation("UpdatedSystemSettings");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Fine", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Reader", b =>
                {
                    b.Navigation("BorrowSlips");

                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Core.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
